In [3]:
import pandas as pd
import folium

# Load the data (replace with the path to your Excel or CSV file)
file_path = 'PostData.xlsx'
data = pd.read_excel(file_path)

data

,gpsID,_date,speed,lat,lng,imei,vin,PelakNo,simcard
0,3,2024-11-12 00:00:00.000,99,36.08843,49.38452,359857084384098,IRGC869z3HX027085,IRI@22الف758@11,9012468889
1,3,2024-11-12 00:00:30.000,100,36.09209,49.37653,359857084384098,IRGC869z3HX027085,IRI@22الف758@11,9012468889
2,3,2024-11-12 00:01:00.000,100,36.09574,49.36853,359857084384098,IRGC869z3HX027085,IRI@22الف758@11,9012468889
3,3,2024-11-12 00:01:30.000,99,36.09950,49.36059,359857084384098,IRGC869z3HX027085,IRI@22الف758@11,9012468889
4,3,2024-11-12 00:02:00.000,99,36.10378,49.35303,359857084384098,IRGC869z3HX027085,IRI@22الف758@11,9012468889
...,...,...,...,...,...,...,...,...,...
95,3,2024-11-12 00:47:07.000,66,36.52694,48.79978,359857084384098,IRGC869z3HX027085,IRI@22الف758@11,9012468889
96,3,2024-11-12 00:47:37.000,68,36.53032,48.79527,359857084384098,IRGC869z3HX027085,IRI@22الف758@11,9012468889
97,3,2024-11-12 00:48:07.000,69,36.53381,48.79066,359857084384098,IRGC869z3HX027085,IRI@22الف758@11,9012468889
98,3,2024-11-12 00:48:37.000,78,36.53766,48.78550,359857084384098,IRGC869z3HX027085,IRI@22الف758@11,9012468889
99,3,2024-11-12 00:49:07.000,78,36.54165,48.78015,359857084384098,IRGC869z3HX027085,IRI@22الف758@11,9012468889

In [7]:
# Initialize the map centered on the average latitude and longitude
map_center = [data['lat'].mean(), data['lng'].mean()]
map_ = folium.Map(location=map_center, zoom_start=12)

# Add each location to the map
for _, row in data.iterrows():
    folium.Marker(
        location=[row['lat'], row['lng']],
        popup=f"Info: {row['speed']}"  # Customize with relevant column info if needed
    ).add_to(map_)

# Save the map to an HTML file
map_.save('map_with_points.html')
print("Map created: map_with_points.html")

Map created: map_with_points.html